#!/usr/bin/env bash
set -e

npm install

if phantom_version="$(phantomjs --version)"; then
  echo "phantomjs ${phantom_version}"
else
  echo "You should install PhantomJS for \`script/test' to work." >&2
fi
