#!/usr/bin/env ruby
files = Dir['*/_posts/*'].reject {|f| f.index('changelog/') == 0 }
missing = []

for file in files
  frontmatter = 0
  docs = false
  examples = false

  IO.foreach(file) do |line|
    if frontmatter < 2
      frontmatter += 1 if line.index('---') == 0
    elsif line =~ /\S/
      docs = true
      examples = true if line =~ /\{%\s*highlight/
    end
  end

  missing << file unless docs
end

num_documented = files.size - missing.size
percent_documented = num_documented.to_f / files.size * 100

warn "methods documented: %d%%" % percent_documented

if percent_documented < 100
  puts missing
  exit 1
else
  exit 0
end
