#!/usr/bin/env ruby
begin
  require 'jekyll/live_site'
rescue LoadError
  unless defined? Gem
    require 'rubygems'
    retry
  end
end

options = Jekyll.configuration('safe' => true)
site = Jekyll::LiveSite.new(options)

if ARGV.empty?
  puts "Building site: %s -> %s" % [ options['source'], options['destination'] ]
  site.process
else
  site.read
  workdir = File.join(Dir.pwd, '')

  site.process_files ARGV do |processed|
    puts processed.sub(workdir, '')
  end
end
